{
    "cart":{
       "action":"https://www.tumerfashion.com/shop/index.php?route=checkout/cart/edit",
       "attention":"", 
       "button_address_add":"اضافة عناوين",
       "button_back":"رجوع",
       "button_cancel":"الغاء",
       "button_cart":"اضافة للسلة",
       "button_change_address":"تغيير العناوين",
       "button_checkout":"انهاء الطلب",
       "button_compare":"اضافة للمقارنة",
       "button_confirm":"تأكيد الطلب",
       "button_continue":"متابعة",
       "button_coupon":"اعتمد التخفيض",
       "button_delete":"حذف",
       "button_download":"تنزيل",
       "button_edit":"تحرير",
       "button_filter":"بحث محسن",
       "button_grid":"شبكة",
       "button_guest":"الطلب للزوار",
       "button_list":"قائمة",
       "button_login":"دخول",
       "button_map":"عرض خريطة جوجل",
       "button_new_address":"عناوين جديدة",
       "button_quote":"أرسل",
       "button_remove":"حذف",
       "button_reorder":"إعادة طلب",
       "button_return":"إرجاع الطلب",
       "button_reviews":"تعليقات",
       "button_reward":"اعتمد النقاط",
       "button_search":"بحث",
       "button_shipping":"اعتمد الشحن",
       "button_shopping":"متابعة",
       "button_submit":"أرسل",
       "button_update":"تحديث الكمية",
       "button_upload":"رفع الملف",
       "button_view":"عرض",
       "button_voucher":"أرسل",
       "button_wishlist":"إضافة لرغباتي",
       "button_write":"كتابة تعليق",
       "checkout":"https://www.tumerfashion.com/shop/index.php?route=checkout/checkout",
       "code":"ar",
       "column_image":"صورة",
       "column_left":{
          "modules":[
             Array
          ]
       },
       "column_model":"النوع",
       "column_name":"الاسم",
       "column_price":"سعر الوحدة",
       "column_quantity":"الكمية",
       "column_right":{
          "modules":[
             Array
          ]
       },
       "column_total":"الاجمالي",
       "content_bottom":{
          "modules":[
             Array
          ]
       },
       "content_top":{
          "modules":[
             Array
          ]
       },
       "continue":"https://www.tumerfashion.com/shop/index.php?route=common/home",
       "country_id":"184",
       "coupon":"",
       "coupon_status":null,
       "date_format_long":"l dS F Y",
       "date_format_short":"Y/m/d",
       "datepicker":"en-gb",
       "datetime_format":"d/m/Y H:i:s",
       "decimal_point":".",
       "direction":"rtl",
       "email_confirm":"<a href=\"%s\" style=\"text-decoration:none; color:#fff; font-weight:bold;\">تأكيد الاشتراك </a>",
       "email_unsubscribe":"<a href=\"%s\">اضغط هنا لإلغاء الاشتراك</a>",
       "entry_country":"الدولة :",
       "entry_coupon":"الرجاء ادخال رمز قسيمة التخفيض",
       "entry_email":"البريد الالكتروني ",
       "entry_email_telephone":"البريد الالكتروني أو رقم الجوال ",
       "entry_password":"كلمة المرور ",
       "entry_postcode":"الرمز البريدي:",
       "entry_submit":"Register your email to receive special offers and promotions.",
       "entry_voucher":"الرجاء ادخال رمز قسيمة الهدايا",
       "entry_zone":"المنطقة / المحافظة:",
       "error_country":"الرجاء الاختيار  ",
       "error_coupon":"تحذير: رمز القسيمة خاطيء, أو انتهى أو تم استخدام الحد الأقصى للقسيمة ",
       "error_curl":"CURL: رمز الخطأ (%s): %s",
       "error_empty":"تحذير: الرجاء ادخال رمز قسيمة التخفيض  ",
       "error_exception":"Error Code(%s): %s in %s on line %s",
       "error_minimum":"أقل كمية طلب لهذا المنتج %s هو %s ",
       "error_no_shipping":"لا توجد طريقة شحن متاحة. الرجاء <a href=\"%s\">الاتصال بنا</a> لمساعدتك  ",
       "error_postcode":"يجب أن يكون بين 2 و 10 رمز  ",
       "error_product":"تحذير: لا توجد منتجات في سلة الشراء الخاصة بك  ",
       "error_recurring_required":"الرجاء الاختيار  ",
       "error_required":"%s مطلوب  ",
       "error_shipping":"مطلوب  ",
       "error_stock":"الطلبات التي بها علامة *** غير متوفرة حالياً أو الكمية المطلوبة غير كافية  ",
       "error_upload_1":"تحذير : حجم الملف المرفوع أكبر من التعريف upload_max_filesize في ملف php.ini  ",
       "error_upload_2":"تحذير : حجم الملف المرفوع أكبر من التعريف MAX_FILE_SIZE في ملف HTML  ",
       "error_upload_3":"تحذير : تم رفع جزء من الملف فقط  ",
       "error_upload_4":"تحذير : لم يتم رفع اي ملف  ",
       "error_upload_6":"تحذير : المجلد المؤقت مفقود  ",
       "error_upload_7":"تحذير : فشل الكتابة إلى القرص  ",
       "error_upload_8":"تحذير : توقف رفع الملف بسبب المدة  ",
       "error_upload_999":"تحذير : رمز الخطأ غير متوفر  ",
       "error_voucher":"تحذير: رمز القسيمة خاطيء, أو انتهى أو تم استخدام الحد الأقصى للقسيمة ",
       "error_warning":"",
       "error_zone":"الرجاء الاختيار  ",
       "heading_title":"سلة الشراء",
       "modules":{
          "coupon":[
             Object
          ],
          "shipping":[
             Object
          ],
          "voucher":[
             Object
          ]
       },
       "postcode":"",
       "products":[
          [
             Object
          ]
       ],
       "shipping":{
          "button_address_add":"اضافة عناوين",
          "button_back":"رجوع",
          "button_cancel":"الغاء",
          "button_cart":"اضافة للسلة",
          "button_change_address":"تغيير العناوين",
          "button_checkout":"انهاء الطلب",
          "button_compare":"اضافة للمقارنة",
          "button_confirm":"تأكيد الطلب",
          "button_continue":"متابعة",
          "button_coupon":"اعتمد التخفيض",
          "button_delete":"حذف",
          "button_download":"تنزيل",
          "button_edit":"تحرير",
          "button_filter":"بحث محسن",
          "button_grid":"شبكة",
          "button_guest":"الطلب للزوار",
          "button_list":"قائمة",
          "button_login":"دخول",
          "button_map":"عرض خريطة جوجل",
          "button_new_address":"عناوين جديدة",
          "button_quote":"أرسل",
          "button_remove":"حذف",
          "button_reorder":"إعادة طلب",
          "button_return":"إرجاع الطلب",
          "button_reviews":"تعليقات",
          "button_reward":"اعتمد النقاط",
          "button_search":"بحث",
          "button_shipping":"اعتمد الشحن",
          "button_shopping":"متابعة",
          "button_submit":"أرسل",
          "button_update":"تحديث الكمية",
          "button_upload":"رفع الملف",
          "button_view":"عرض",
          "button_voucher":"أرسل",
          "button_wishlist":"إضافة لرغباتي",
          "button_write":"كتابة تعليق",
          "code":"ar",
          "column_image":"صورة",
          "column_model":"النوع",
          "column_name":"الاسم",
          "column_price":"سعر الوحدة",
          "column_quantity":"الكمية",
          "column_total":"الاجمالي",
          "countries":[
             Array
          ],
          "country_id":"184",
          "date_format_long":"l dS F Y",
          "date_format_short":"Y/m/d",
          "datepicker":"en-gb",
          "datetime_format":"d/m/Y H:i:s",
          "decimal_point":".",
          "direction":"rtl",
          "entry_country":"الدولة :",
          "entry_coupon":"الرجاء ادخال رمز قسيمة التخفيض",
          "entry_postcode":"الرمز البريدي:",
          "entry_zone":"المنطقة / المحافظة:",
          "error_country":"الرجاء الاختيار  ",
          "error_coupon":"تحذير: رمز القسيمة خاطيء, أو انتهى أو تم استخدام الحد الأقصى للقسيمة ",
          "error_curl":"CURL: رمز الخطأ (%s): %s",
          "error_empty":"تحذير: الرجاء ادخال رمز قسيمة التخفيض  ",
          "error_exception":"Error Code(%s): %s in %s on line %s",
          "error_minimum":"أقل كمية طلب لهذا المنتج %s هو %s ",
          "error_no_shipping":"لا توجد طريقة شحن متاحة. الرجاء <a href=\"%s\">الاتصال بنا</a> لمساعدتك  ",
          "error_postcode":"يجب أن يكون بين 2 و 10 رمز  ",
          "error_product":"تحذير: لا توجد منتجات في سلة الشراء الخاصة بك  ",
          "error_recurring_required":"الرجاء الاختيار  ",
          "error_required":"%s مطلوب  ",
          "error_shipping":"مطلوب  ",
          "error_stock":"الطلبات التي بها علامة *** غير متوفرة حالياً أو الكمية المطلوبة غير كافية  ",
          "error_upload_1":"تحذير : حجم الملف المرفوع أكبر من التعريف upload_max_filesize في ملف php.ini  ",
          "error_upload_2":"تحذير : حجم الملف المرفوع أكبر من التعريف MAX_FILE_SIZE في ملف HTML  ",
          "error_upload_3":"تحذير : تم رفع جزء من الملف فقط  ",
          "error_upload_4":"تحذير : لم يتم رفع اي ملف  ",
          "error_upload_6":"تحذير : المجلد المؤقت مفقود  ",
          "error_upload_7":"تحذير : فشل الكتابة إلى القرص  ",
          "error_upload_8":"تحذير : توقف رفع الملف بسبب المدة  ",
          "error_upload_999":"تحذير : رمز الخطأ غير متوفر  ",
          "error_zone":"الرجاء الاختيار  ",
          "heading_title":"الشحن المتوقع",
          "postcode":"",
          "shipping_method":"",
          "text_all_zones":"جميع الاقسام",
          "text_coupon":"قسيمة التخفيض(%s)",
          "text_credit":"رصيد المتجر",
          "text_day":"يوم",
          "text_empty":"سلة الشراء فارغة  ",
          "text_home":"الرئيسية",
          "text_items":"%s منتجات - %s",
          "text_loading":"جاري ...",
          "text_login":"تنبيه : يجب عليك <a href=\"%s\"> تسجيل الدخول </a> أو <a href=\"%s\">إنشاء حساب </a> لمشاهدة السعر  ",
          "text_month":"شهر",
          "text_more":"عرض المزيد",
          "text_next":"الخيارات المتاحة في سلة الشراء",
          "text_next_choice":"الرجاء الاختيار اذا كنت تمتلك رمز تخفيض أو نقاط مكافآت أو معاينة طرق الشحن المتوقعة لمنطقتك.",
          "text_no":"لا",
          "text_no_results":"لاتوجد نتائج  ",
          "text_none":" --- لا يوجد --- ",
          "text_order_id":"رقم الطلب : #%s",
          "text_pagination":"عرض %d الى %d من %d (%d صفحات)",
          "text_payment_cancel":"%s كل %d %s حتى يتم الغاؤها",
          "text_payment_description":"%s كل %d %s الى %d مدفوعات",
          "text_payment_recurring":"ملف المدفوعات",
          "text_points":"نقاط المكافآت: %s",
          "text_recurring":"%s كل %s %s",
          "text_recurring_item":"مدفوعات متكررة",
          "text_remove":"نجاح: تم تعديل محتويات سلة الشراء  ",
          "text_select":" --- الرجاء الاختيار --- ",
          "text_semi_month":"نصف شهري",
          "text_shipping":"ادخل بيانات الشحن الخاصة بك للحصول على الشحن المتوقع لطلبك.",
          "text_shipping_method":"الرجاء اختيار طريقة الشحن المناسبة لك.",
          "text_sub_total":"الاجمالي",
          "text_success":"تم تطبيق الشحن المتوقع  ",
          "text_total":"الاجمالي النهائي",
          "text_trial":"%s كل %s %s الى %s مدفوعات ",
          "text_trial_description":"%s كل %d %s الى %d مدفوعات",
          "text_week":"اسبوع",
          "text_year":"سنة",
          "text_yes":"نعم",
          "thousand_point":",",
          "time_format":"h:i:s A",
          "zone_id":""
       },
       "shipping_method":"",
       "shipping_status":null,
       "success":"",
       "text_account":"حسابي",
       "text_address":"دفتر العناويين",
       "text_affiliate":"نظام العمولة",
       "text_all":"اذهب الى قسم",
       "text_all_zones":"جميع الاقسام",
       "text_bestseller":"الأكثر مبيعاً",
       "text_cart":"معاينة السلة",
       "text_category":"أقسام الموقع",
       "text_checkout":"إنهاء الطلب",
       "text_contact":"اتصل بنا",
       "text_contactus":"تواصل معنا",
       "text_copyrights":"&copy; جميع الحقوق محفوظة لدى %s %s",
       "text_coupon":"قسيمة التخفيض(%s)",
       "text_credit":"رصيد المتجر",
       "text_currency":"العملة",
       "text_day":"يوم",
       "text_download":"ملفات التنزيل الرقمية",
       "text_dublicate":"هذا البريد الالكتروني موجود بالفعل ",
       "text_edit":"تحرير الحساب",
       "text_email":"البريد الالكتروني",
       "text_empty":"سلة الشراء فارغة  ",
       "text_extra":"إضافات",
       "text_forgotten":"نسيت كلمة المرور؟",
       "text_home":"الرئيسية",
       "text_information":"معلومات",
       "text_items":"%s منتجات - %s",
       "text_language":"اللغة",
       "text_latest":"وصل حديثاً",
       "text_loading":"جاري ...",
       "text_login":"تنبيه : يجب عليك <a href=\"%s\"> تسجيل الدخول </a> أو <a href=\"%s\">إنشاء حساب </a> لمشاهدة السعر  ",
       "text_logout":"خروج",
       "text_manufacturer":"الشركات",
       "text_month":"شهر",
       "text_more":"عرض المزيد",
       "text_new_user":"ليس لديك حساب",
       "text_newsletter":"القائمة البريدية",
       "text_next":"الخيارات المتاحة في سلة الشراء",
       "text_next_choice":"الرجاء الاختيار اذا كنت تمتلك رمز تخفيض أو نقاط مكافآت أو معاينة طرق الشحن المتوقعة لمنطقتك.",
       "text_no":"لا",
       "text_no_results":"لاتوجد نتائج  ",
       "text_none":" --- لا يوجد --- ",
       "text_order":"طلباتي",
       "text_order_id":"رقم الطلب : #%s",
       "text_pagination":"عرض %d الى %d من %d (%d صفحات)",
       "text_password":"كلمة المرور",
       "text_payment_cancel":"%s كل %d %s حتى يتم الغاؤها",
       "text_payment_description":"%s كل %d %s الى %d مدفوعات",
       "text_payment_recurring":"ملف المدفوعات",
       "text_points":"نقاط المكافآت: %s",
       "text_powered":"تصميم وتطوير",
       "text_recurring":"%s كل %s %s",
       "text_recurring_item":"مدفوعات متكررة",
       "text_register":"تسجيل",
       "text_register_now":"سجل الآن",
       "text_remove":"نجاح: تم تعديل محتويات سلة الشراء  ",
       "text_return":"المنتجات المرتجعة",
       "text_reward":"نقاط المكافآت",
       "text_search":"بحث",
       "text_select":" --- الرجاء الاختيار --- ",
       "text_semi_month":"نصف شهري",
       "text_service":"خدمات العملاء",
       "text_shipping":"ادخل بيانات الشحن الخاصة بك للحصول على الشحن المتوقع لطلبك.",
       "text_shipping_detail":"ادخل بيانات الشحن الخاصة بك للحصول على الشحن المتوقع لطلبك.",
       "text_shipping_estimate":"الشحن المتوقع",
       "text_shipping_method":"الرجاء اختيار طريقة الشحن المناسبة لك.",
       "text_shopping_cart":"سلة الشراء",
       "text_sitemap":"خريطة الموقع",
       "text_special":"العروض المميزة",
       "text_sub_total":"الاجمالي",
       "text_subscribe":"اشترك",
       "text_success":" تم إضافة <a href=\"%s\">%s</a> إلى <a href=\"%s\"> سلة الشراء </a> ",
       "text_telephone":"الهاتف",
       "text_total":"الاجمالي النهائي",
       "text_transaction":"رصيدي",
       "text_trial":"%s كل %s %s الى %s مدفوعات ",
       "text_trial_description":"%s كل %d %s الى %d مدفوعات",
       "text_use_coupon":"استخدم قسيمة التخفيض",
       "text_use_voucher":"استخدم قسائم الهدايا",
       "text_voucher":"قسيمة الهدايا(%s)",
       "text_week":"اسبوع",
       "text_wishlist":"قائمة رغباتي",
       "text_year":"سنة",
       "text_yes":"نعم",
       "thousand_point":",",
       "time_format":"h:i:s A",
       "totals":[
          [
             Object
          ],
          [
             Object
          ]
       ],
       "visitor_checkout":true,
       "voucher":"",
       "voucher_status":null,
       "vouchers":[
          
       ],
       "weight":"",
       "zone_id":""
    },
    "cartItemsCount":1,
    "contact":{
       "address":"",
       "android_url":"https://google.com",
       "email":"",
       "facebook":"https://www.facebook.com/",
       "instagram":"https://www.instagram.com/tumer_kinz_casual/",
       "ios_url":"https://apple.com",
       "map":{
          "lat":"",
          "lng":""
       },
       "maroof":"",
       "opening":"",
       "phone":"201152636572",
       "sharing":"شارك هذا التطبيق لتجربة أفضل فى التسوق",
       "snapchat":"https://www.snapchat.com/",
       "twitter":"https://twitter.com/messages"
    },
    "cookie":"e1b2f2f78f1568c2059a2c3f09",
    "countries":[
       {
          "address_format":"",
          "country_id":"184",
          "iso_code_2":"SA",
          "iso_code_3":"SAU",
          "name":"السعودية",
          "name_en":"Saudi Arabia",
          "postcode_required":"0",
          "status":"1"
       }
    ],
    "currencies":[
       {
          "code":"SAR",
          "symbol_left":" SAR",
          "symbol_right":" ريال",
          "title":"الريال السعودي"
       }
    ],
    "currency":{
       "code":"SAR",
       "decimal_point":".",
       "symbol_left":" SAR",
       "symbol_right":" ريال",
       "thousand_point":","
    },
    "direction":"rtl",
    "language":"ar",
    "languages":[
       {
          "code":"en-gb",
          "dir":"ltr",
          "image":"gb.png",
          "name":"English"
       },
       {
          "code":"ar",
          "dir":"rtl",
          "image":"ar.png",
          "name":"العربية"
       }
    ],
    "logged":null,
    "settings":{
       "affiliate_setting":null,
       "analytics_id":null,
       "connection_type":null,
       "gcm_sender":null,
       "license_key":null
    },
    "wishlist":[
       
    ]
 }