export default {
  login: 'تسجيل دخول',
  passForgot: 'هل نسيت كلمة المرور؟',
  email: 'البريد الإلكتروني',
  password: 'كلمة المرور',
  confirmPassword: 'تأكيد كلمة المرور',
  enter: 'دخول',
  register: 'تسجيل جديد',
  enterEmail:
    'أدخل البريد الالكتروني المرتبط مع حسابك. انقر على متابعه ليتم إرسال رابط انشاء كلمة مرور جديدة إلى بريدك الخاص',
  send: 'إرسال',
  resetPass: 'إعادة تعيين كلمة المرور',
  oldPass: 'كلمة المرور الحالية',
  newPass: 'كلمة المرور الجديدة',
  confirmNewPass: 'تأكيد كلمة المرور الجديدة',
  addNewAccount: 'تسجيل حساب جديد',
  firstName: 'الاسم الأول',
  lastName: 'الاسم الأخير',
  phone: 'رقم الجوال',
  iRead: 'لقد قرأت ووافقت على',
  terms: 'الشروط والأحكام',
  Register: 'تسجيل',
  ifHave: 'إذا كان لديك حساب معنا',
  Login: 'سجل دخول',
  Logout: 'تسجيل خروج',
  createdSuccessfully: 'لقد تم انشاء الحساب بنجاح',
  YouCanBenefit: 'يمكنك الآن الاستفادة من امتيازات عضوية حسابك معنا في المتجر',
  searchFor: 'عن ماذا تبحث؟',
  dokanNew: 'جديد دكان تحف',
  displayMore: 'عرض المزيد',
  featuredProducts: 'المنتجات المميزة',
  newArticles: 'أحدث المقالات',
  rights: 'جميع الحقوق محفوظة © تومر 2022',
  readMore: 'قراءة المزيد',
  bestSeller: 'الأكثر مبيعًا',
  productsCompare: 'مقارنة المنتجات',
  sortBy: 'الترتيب حسب',
  SR: 'ريال',
  display: 'عرض',
  resultsSearchFor: 'نتيجة من البحث عن -',
  cart: 'السلة',
  categories: 'الأقسام',
  more: 'الـمزيد',
  myAccount: 'حسابي',
  department: 'القسم',
  price: 'السعر',
  rate: 'تقييم المنتج',
  discount: 'التخفيضات',
  searchFilters: 'فلترة البحث',
  reset: 'إعادة تعيين',
  SortBy: 'الفرز بواسطة',
  default: 'الافتراضي',
  nameAToZ: 'الاسم من أ - ي',
  nameZToA: 'الاسم من ي - أ',
  priceLow: 'السعر (منخفض > مرتفع)',
  priceHight: 'السعر (مرتفع > منخفض)',
  hightRate: 'تقييم مرتفع',
  lowRate: 'تقييم منخفض',
  typeAToZ: 'النوع (أ - ي)',
  typeZToA: 'النوع (ي - أ)',
  tall: 'الطول',
  width: 'العرض',
  material: 'الخامة',
  height: 'الارتفاع',
  description: 'الوصف',
  comments: 'التعليقات',
  addComment: 'إضافة تعليق',
  theName: 'الاسم',
  typeYourComment: 'اكتب تعليقك هنا',
  addRatings: 'اضف علامات التقييم',
  otherProductsYouLike: 'منتجات اخرى ستنال إعجابك',
  wood: 'الخشب الطبيعي',
  CM: 'سم',
  buyNow: 'اشتري الآن',
  AboutUs: 'من نحن',
  ShippingandDelivery: 'الشحن و التوصيل',
  ReturnPolicy: 'سياسة الارجاع',
  PrivacyPolicy: 'سياسة الخصوصية',
  Blog: 'المدونة',
  ContactUs: 'اتصل بنا',
  Settings: 'الإعدادات',
  SharetheApp: 'مشاركة التطبيق',
  RateApp: 'تقييم التطبيق على المتجر',
  Home: 'الرئيسية',
  fullName: 'الاسم بالكامل',
  messageContent: 'نص الرسالة',
  SendInquiry: 'ارسل لنا استفسارك',
  'Follow us on social media': 'تابعنا على مواقع التواصل',
  haveNoAccount: 'ليس لديك حساب؟',
  registerNow: 'سجل الآن',
  vistorEnter: 'تصفح التطبيق كزائر',
  language: 'اللغة',
  productModel: 'الماركة',
  currency: 'العملة',
  notifications: 'الاشعارات',
  EditAccountInformation: 'تحرير معلومات الحساب',
  changePassword: 'تغيير كلمة المرور',
  bookAddresses: 'دفتر العناوين',
  WishList: 'قائمة رغباتي',
  MailingList: 'القائمة البريدية',
  orderBook: 'سجل الطلبات',
  RewardsPoints: 'نقاط المكافآت',
  ReturnRequests: 'طلبات الإرجاع',
  myOrders: 'طلباتى',
  saveChanges: 'حفظ التغييرات',
  SubscribeMailingList: 'الاشتراك في القائمة البريدية',
  yes: 'نعم',
  no: 'لا',
  save: 'حفظ',
  Delete: 'حذف',
  Edit: 'تحرير',
  recentlyArrived: 'وصل حديثا',
  select: 'حدد الخيار المناسب',
  size: 'المقاس',
  theColor: 'اللون',
  similarProducts: 'منتجات مشابهة',
  addToCart: 'اضف إلى السلة',
  enterVoucher: 'ادخل قسيمة الهدايا',
  enterDiscount: 'ادخل قسيمة التخفيض',

  apply: 'تطبيق',
  total: 'الإجمالي',
  'VAT(15%)': 'ضريبة القيمة المضافة (15%)',
  finalTotal: 'الاجمالي النهائي',
  checkout: 'انهاء الطلب',
  thanks: 'شكرا جزيلا على ثقتكم',
  ContinueShopping: 'متابعة التسوق',
  orderRecived: 'عميلنا العزيز تم استلام طلبك بنجاح، ونفيدكم بأن رقم الطلب هو',
  accountAndBilling: 'الحساب وتفاصيل الفاتورة',
  Country: 'البلد',
  regionProvince: 'المنطقة/ المحافظة',
  detailedAddress: 'العنوان بالتفصيل',
  iWantReg: 'أريد تسجيل حساب بالمتجر لاستخدامه مستقبلاً',
  myShippingAddress: 'عنوان الشحن وعنوان الدفع الخاص بي متطابق',
  ShippingMethod: 'طريقة الشحن',
  PaymentMethod: 'طريقة الدفع',
  normalShipping: 'الشحن العادي',
  AramexShipping: 'شحن ارامكس',
  PayBy: 'الدفع عن طرق ( فيزا / ماستر كارد / مدى )',
  PayWhenRecieving: 'الدفع عند الاستلام',
  buyCart: 'سلة الشراء',
  changeAddress: 'تغيير العنوان',
  showOrderDetails: 'عرض تفاصيل الطلب',
  orderNumber: 'رقم الطلب',
  orderDate: 'تاريخ الطلب',
  OrderRecived: 'تم استلام الطلب',
  Processing: 'جاري المعالجة',
  complete: 'مكتمل',
  Canceled: 'تم الإلغاء',
  Cancel: 'الغاء',
  ReturnNumber: 'رقم طلب الارجاع',
  orderDetailsNum: 'تفاصيل الطلب رقم # ',
  payAddress: 'عنوان الدفع',
  shippingAddress: 'عنوان الشحن',
  shippingCost: 'تكلفة الشحن',
  buyAgain: 'شراء مرة اخرى',
  returnOrder: 'إرجاع الطلب',
  quantity: 'الكمية: ',
  rewardPoints: 'نقاط المكافآت',
  totalPoints: 'إجمالي النقاط',
  points: 'النقاط',
  addedDate: 'تاريخ الاضافة',
  decription: 'الوصف',
  ReturnDetailsNum: 'تفاصيل طلب الارجاع رقم #',
  ReturntNumber: 'رقم طلب الإرجاع',
  returnReason: 'سبب الارجاع',
  hasOpened: 'هل تم فتح المنتج؟',
  retunDetails: 'تفاصيل أو عيوب أخرى',
  ClickVoiceSearch: 'اضغط هنا للبحث عن منتج بصوتك',
  SpeakTheName: 'قم بنطق اسم المنتج الذي تبحث عنه',
  addAddress: 'إضافة عنوان جديد',
  city: 'المدينة',
  setAsDefault: 'تعيين هذا العنوان كافتراضى',
  TermsConditions: 'الشروط والاحكام',
  plaseApprove: 'برجاء الموافقة أولا على الشروط والأحكام',
  noResult: 'لا يوجد منتجات بهذا الاسم',
  messageSent: 'تم ارسال الاستفسار بنجاح',
  selectCountry: 'رجاء قم باختيار الدولة أولا حتى تظهر المناطق',
  saveChangesSuccess: 'تم حفظ التغييرات',
  notFound: 'لايوجد',
  noComments: 'لا يوجد تعليقات',
  noAddressess: 'لا يوجد عناوين, برجاء كتابة عنوانك',
  moreComments: 'عرض المزيد من التعليقات',
  addedToFav: 'تمت اضافة المنتج الى المفضلة',
  removeFromFav: 'تمت ازالة المنتج من المفضلة',
  addedToCart: 'تمت اضافة المنتج الى السلة',
  productName: 'اسم المنتج',
  isProductOpen: 'هل تم فتح المنتج',
  otherNotes: 'ملاحظات أخرى',
  Brand: 'الموديل',
  status: 'الحالة',
  addedToCompare: 'تمت الاضافة الى صفحة المقارنات ',
  addedToCompareError: 'لم تتم الاضافة',
  voucherAccepted: 'تم قبول خصم قسيمة الهدايا ',
  cartIsEmpty: 'سلة الشراء فارغة',
  typeSomthing: 'رجاء قم بكتابة ما تريد البحث عنه',
  noCategories: 'لايوجد أقسام حتى الان',
  youMustChooseChoices: 'رجاء يجب عليك تحديد اختيارات المنتج',
  mustBeLoggedIn: 'يجب تسجيل الدخول',
  toAccessThisPage: 'للدخول الى هذه الصفحة يجب تسجيل الدخول',
  shareMessage: 'احصل على هذا المنتج بأفضل جودة وأقل سعر',
  addedd: 'تمت الاضافة بنجاج',
  all: 'الكل',
  priceWithoutTax: 'السعر بدون ضريبة',
  noShipingToThisAddress: 'لا يوجد شحن الى هذا العنوان',
  noPaymentToThisAddress: 'لا يوجد طرق دفع متاحة لهذا العنوان',
  invalidPhone: 'رقم هاتف غير صحيح',
  continue: 'متابعة',
  pleaseTryAgain: `رجاء حاول مرة أخرى`,
  Add: 'أضف',
  'Return Product': 'ارجاع المنتج',
  'Request Sent': 'تم ارسال الطلب بنجاح',
  'Enter Reward Points': 'أدخل نقاط المكافأة',
  'No Orders': 'لايوجد طلبات لديك حتى الأن',
  "You don't have addressess": 'ليس لديك أى عناوين يرجى اضافة عناوين',
  noEnoughQty: 'عذرا هذه الكمية من المنتج غير متوفر حيث الكمية المتاحة هى ',
  noQty: 'الكمية منتهية',
  plzReduceQty: 'هذه الكمية غير متاحة يرجى تقليل الكمية',
  Search: 'بحث',
  byCommenting: 'بالتعليق أنت توافق على ',
  delAccount: 'حذف الحساب',
  areUSureUWantDeleteUrAccount: 'هل انت متاكد انك تريد حذف حسابك؟',
  byDelete:
    'بضغطك على زر حذف  فانت موافق على حذف حسابك بالكامل وجميع بياناتك من قاعدة البيانات الخاصة بنا ولن تتمكن من استرجاعها أبدا',
  accountDeleted: 'تم حذف الحساب بنجاح',
  resetLinkSent:
    'تم ارسال رابط اعداد كلمة المرور الي البريد الالكتروني الخاص بك ',
  spamNote:
    'ملحوظة هامة: اذا لم تصلك الرسالة في صندوق الرسائل  برجاء التحقق من صندوق Spam ',

  fillAllFields: 'برجاء التأكد من ملئ كافة الحقول',
  "passwordsDon'tMatch": 'كلمتا المرور غير متطابقتين',
  lessProdsNum: 'أقل عدد ممكن من المنتجات هو 0',
  updatePassErr: 'خطأ فى تحديث كلمة المرور',
  passUpdated: 'تم تحديث كلمة المرور',
};
