export default {
  login: 'Login',
  passForgot: 'Do you forget password?',
  email: 'Email',
  password: 'Password',
  enter: 'Login',
  register: 'Register',
  enterEmail:
    'enter the email address that is connected to your account. Click Continue and a link to create a new password will be sent to your inbox',
  oldPass: 'Old Password',
  resetPass: 'Password Reset',
  newPass: 'The new password',
  confirmNewPass: 'Confirm the new password',
  reset: 'Reset',
  addNewAccount: 'Register a new account',
  firstName: 'First Name',
  lastName: 'Last Name',
  phone: 'Phone Number',
  iRead: 'I Agree to the',
  terms: ' Terms and Conditions',
  Register: 'Register',
  ifHave: 'If you have an account with us,',
  Login: ' log in',
  confirmPassword: 'Confirm Password',
  createdSuccessfully: 'The account has been created successfully',
  YouCanBenefit:
    'You can now benefit from the privileges of membership of your account with us in the store',
  searchFor: 'What are you looking for?',
  dokanNew: 'New antiques',
  displayMore: 'Show more',
  featuredProducts: 'Featured Products',
  newArticles: 'New Articles',
  rights: 'All rights reserved © Tumer 2022',
  readMore: 'Read More',
  bestSeller: 'best seller',
  productsCompare: 'Compare',
  sortBy: 'Sort by',
  searchFilters: 'Search filters',
  SR: 'SR',
  test: 'test',
  display: 'Display',
  resultsSearchFor: 'results from search for -',
  cart: 'Cart',
  categories: 'Categories',
  more: 'More',
  myAccount: 'Account',
  department: 'Department',
  price: 'Price',
  rate: 'Rate',
  discount: 'Discount',
  SortBy: 'Sort By',
  Logout: 'Logout',
  default: 'Default',
  nameAToZ: 'Name A To Z',
  nameZToA: 'Name Z To A',
  priceLow: 'Price ( Low > Hight )',
  priceHight: 'Price ( Low < Hight )',
  hightRate: 'Hight Rate',
  lowRate: 'Low Rate',
  typeAToZ: 'Type A To Z',
  typeZToA: 'Type Z To A',
  tall: 'Tall',
  width: 'Width',
  material: 'Material',
  height: 'Height',
  description: 'Description',
  comments: 'Comments',
  addComment: 'Add comment',
  theName: 'Name',
  typeYourComment: 'Type your comment',
  addRatings: 'Add ratings',
  otherProductsYouLike: 'Other products you will like',
  wood: 'Wood',
  CM: 'CM',
  buyNow: 'Buy Now',
  AboutUs: 'About us',
  ShippingandDelivery: 'Shipping and delivery',
  ReturnPolicy: 'Return policy',
  PrivacyPolicy: 'Privacy policy',
  Blog: 'Blog',
  ContactUs: 'Contact us',
  Settings: 'Settings',
  SharetheApp: 'Share the app',
  RateApp: 'Rate App',
  fullName: 'Full name',
  messageContent: 'Message content',
  SendInquiry: 'Send us your inquiry',
  'Follow us on social media': 'Follow us on social media',
  haveNoAccount: 'Have No Account?',
  registerNow: 'Register',
  vistorEnter: 'Login As Visitor',
  language: 'Language',
  currency: 'Currency',
  notifications: 'Notifications',
  EditAccountInformation: 'Edit account information',
  changePassword: 'Change Password',
  bookAddresses: 'Book Addresses',
  WishList: 'Wish List',
  MailingList: 'Mailing List',
  orderBook: 'Orders',
  RewardsPoints: 'Rewards Points',
  ReturnRequests: 'Return Requests',
  myOrders: 'My Orders',
  saveChanges: 'Save Changes',
  SubscribeMailingList: 'Subscribe to the mailing list',
  yes: 'Yes',
  no: 'No',
  save: 'Save',
  Delete: 'Delete',
  Edit: 'Edit',
  recentlyArrived: 'Recently Arrived',
  select: 'Select',
  size: 'Size',
  theColor: 'Color',
  similarProducts: 'Similar products',
  addToCart: 'Add To Cart',
  enterVoucher: 'Enter the gift voucher',
  enterDiscount: 'Enter the discount voucher',
  apply: 'Apply',
  total: 'Total',
  'VAT(15%)': 'Value Added Tax (15%)',
  finalTotal: 'final total',
  checkout: 'check out',
  thanks: 'Thank you very much for your trust',
  ContinueShopping: 'Continue shopping',
  orderRecived:
    'Dear customer, your order has been received successfully, and we inform you that the order number is',
  accountAndBilling: 'Account and billing details',
  Country: 'Country',
  regionProvince: 'Region/Province',
  detailedAddress: 'Detailed address',
  iWantReg: 'I want to register an account in the store for future use',
  myShippingAddress: 'My shipping address and payment address match',
  ShippingMethod: 'Shipping method',
  PaymentMethod: 'Payment method',
  normalShipping: 'normal shipping',
  AramexShipping: 'Aramex Shipping',
  PayBy: 'Payment by (Visa / Master Card / Mada)',
  PayWhenRecieving: 'Pay when recieving',
  buyCart: 'Cart',
  changeAddress: 'Change',
  showOrderDetails: 'Show Order Details',
  orderNumber: 'Order Number',
  orderDate: 'Order Date',
  OrderRecived: 'Recived',
  Processing: 'Processing in progress',
  complete: 'Complete',
  Canceled: 'Canceled',
  Cancel: 'Cancel',
  ReturnNumber: 'Return Number',
  orderDetailsNum: 'Order Number',
  payAddress: 'Pay Address',
  shippingAddress: 'Shipping Address',
  shippingCost: 'Shipping Cost',
  buyAgain: 'Buy Again',
  returnOrder: 'Return Order',
  quantity: 'Quantity: ',
  rewardPoints: 'Reward Points',
  totalPoints: 'Total Points',
  points: 'Points',
  addedDate: 'Added date',
  decription: 'Description',
  ReturnDetailsNum: 'Return Request Details #',
  ReturntNumber: 'Return request number',
  returnReason: 'Reason for return',
  hasOpened: 'Has the product been opened?',
  retunDetails: 'Other details or defects:',
  ClickVoiceSearch: 'Click here to search for a product with your voice',
  SpeakTheName: 'Speak the name of the product you are looking for',
  addAddress: 'Add new address',
  city: 'City',
  setAsDefault: 'Set as default',
  TermsConditions: 'Terms and Conditions',
  plaseApprove: 'Please first agree to the terms and conditions',
  noResult: 'No Result',
  noAddressess: 'No Addressess',
  messageSent: 'Message Sent Successfuly',
  selectCountry: 'Please select country first',
  saveChangesSuccess: 'Changes Saved',
  notFound: 'Not Found',
  moreComments: 'See more comments',
  noComments: 'No comments ',

  addedToFav: 'Added To Favorites',
  removeFromFav: 'Removed From Favorites',
  addedToCart: 'Added To Cart',

  productName: 'Product name',
  productModel: 'Model',
  isProductOpen: 'Has the product been opened?',
  otherNotes: 'Other notes',
  Brand: 'Brand',
  status: 'status',
  addedToCompare: 'Added to comparison page',
  addedToCompareError: 'Not added',
  voucherAccepted: 'Gift voucher discount accepted.',
  cartIsEmpty: 'Cart Is Empty!',
  mustBeLoggedIn: 'You must be logged in',
  toAccessThisPage: 'To access this page, you must be logged in',
  noCategories: 'No categories',
  typeSomthing: 'Please type somthing in search input!',
  youMustChooseChoices: 'Please choose your product options',
  shareMessage: 'Get this product with lower price and good quality',
  addedd: 'Addedd',
  all: 'All',
  priceWithoutTax: 'Price without tax',
  noShipingToThisAddress: 'No Shipping options are available',
  noPaymentToThisAddress: 'No Payment options are available',
  invalidPhone: 'Invalid phone number',
  continue: 'Continue',
  pleaseTryAgain: 'Please Try Again',
  Add: 'Add',
  noEnoughQty:
    'Sorry, this quantity of the product is not available as the available quantity is ',
  noQty: 'Sold out',
  plzReduceQty: 'This quantity is not available, please reduce the quantity',
  Search: 'Search',
  byCommenting: 'By commenting, you agree to the ',
  delAccount: 'Delete Account',
  areUSureUWantDeleteUrAccount: 'Are you sure you want to delete your account?',
  byDelete:
    'By clicking on the delete button, you agree to completely delete your account and all your data from our database and you will never be able to retrieve it',
  accountDeleted: 'The account has been deleted successfully',
  resetLinkSent: 'A password reset link has been sent to your email',
  spamNote:
    'Important note: If you did not receive the message in your inbox, please check your spam',

  fillAllFields: 'Please Fill All Fields',
  "passwordsDon'tMatch": "Passwords don't match",
  lessProdsNum: 'Minimum number you can add is 0',
  updatePassErr: 'Update password error',
  passUpdated: 'Password updated',
};
